fixed and renamed options, added --clean

diff --git a/tpdf b/tpdf
--- a/tpdf
+++ b/tpdf
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# version 0.037
+# version 0.04
 
 # copyright Alex Dunn 2011
 
@@ -26,9 +26,10 @@ bibpath=
 shortbib=
 bibext=
 backhome=$(pwd)
-mode="1"
+mode="2"
 bibon="1"
-bttm="0"
+clean=
+cleaner=
 pdftarget=
 pdfoptions=""
 bibtarget=
@@ -55,6 +56,23 @@ then
 	echo "---The first file must be a .tex file."
 	exit 1
 else
+	if [ "$clean" = "1" ]
+	then
+		ls ./*/*/*.pdf
+		echo -n "---Delete these PDFs? (y/n) "
+		read cleaner
+		until [ "$cleaner" = "cleen" ]
+			do
+			case $cleaner in
+				n		)	cleaner="cleen"
+							;;
+				y | ""	)	rm ./*/*/*.pdf
+							cleaner="cleen"
+							;;
+				*		)	cleaner="cleen"
+			esac
+		done
+	fi
 	texpath=$(dirname "$texfile")
 	shorttex=$(basename -s .tex "$texfile")
 	pdftarget="$shorttex"
@@ -211,39 +229,55 @@ else
 			"-"*				)	while [[ "$1" = "-"* ]]
 									do
 										case $1 in
-											"--"*	)	if [ "$1" = "--normal" ]
-														then
-															#echo "OINK"
-															#exit 0
-															mode="2"
-														elif [ "$1" = "--bibtex" ]
-														then
-															#echo "OINK"
-															#exit 0
-															bibon="2"
-														else
-															echo "---Invalid command."
+											"--"*		)	if [ "$1" = "--stamp" ]
+															then
+																if [ "$mode" != "1" ]
+																then
+																	mode="1"
+																fi
+															elif [ "$1" = "--bibtex" ]
+															then
+																if [ "$bibon" != "2" ]
+																then
+																	bibon="2"
+																fi
+															elif [ "$1" = "--clean" ]
+															then
+																if [ "$clean" != "1" ]
+																then
+																	clean="1"
+																fi
+															else
+																echo "---Invalid command."
+																exit 1
+															fi
+															shift
+															;;
+											"-"*[!bsc]*	)	echo "---Invalid command."
 															exit 1
-														fi
-														shift
-														;;
-											*		)	if [[ "$1" = *"b"* ]]
-														then
-															if [ "$bibon" != "2" ]
+															;;
+											*			)	if [[ "$1" = *"b"* ]]
 															then
-																echo "Bob"
-																bibon="2"
+																if [ "$bibon" != "2" ]
+																then
+																	bibon="2"
+																fi
 															fi
-														fi
-														if [[ "$1" = *"n"* ]]
-														then
-															if [ "$mode" != "2" ]
+															if [[ "$1" = *"s"* ]]
 															then
-																echo "Nob"
-																mode="2"
+																if [ "$mode" != "1" ]
+																then
+																	mode="1"
+																fi
 															fi
-														fi
-														shift
+															if [[ "$1" = *"c"* ]]
+															then
+																if [ "$clean" != "1" ]
+																then
+																	clean="1"
+																fi
+															fi
+															shift
 										esac
 									done
 									;;
